In [145]:
import cv2
import numpy as np
from MagicBox.dataset.artificial_dataset import ArtificialDataset
from utils import plot_imgs

%load_ext autoreload
%autoreload 2
%matplotlib inline


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [146]:
config = {
    'data_path': '../dataset',
    'suffix': 'v1',
    'primitives': 'all',
    'truncate': {'draw_ellipses': 0.3, 'draw_stripes': 0.2, 'gaussian_noise': 0.1},
    'preprocessing': {'resize': [120, 160], 'blur_size': 21}
}

dataset = ArtificialDataset('test', config)


In [147]:
def draw_keypoints(img, corners, color):
    keypoints = [cv2.KeyPoint(c[1], c[0], 1) for c in np.stack(corners).T]
    return cv2.drawKeypoints(img.astype(np.uint8), keypoints, None, color=color)
def display(d):
    return draw_keypoints(d['image'][..., 0], np.where(d['keypoint_map']), (0, 255, 0))


In [149]:
item = dataset.__getitem__(1)
print(item[0].shape, item[1].shape)

# for i in range(8):
#     print()
#     plot_imgs([display(dataset.__getitem__(i))/255. for _ in range(4)], dpi=200)

(1, 120, 160) (1, 120, 160)


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
